version: "3"
services: 
  auth:
    image: "auth/vk"
    restart: always
    ports: 
      - "3000:3000"
  redis-server:
    image: "redis"
    restart: always
    volumes: 
      - redis_data:/data
    ports: 
      - "6379:6379"

volumes: 
  redis_data: